// Builds an extension package.
//
//   deno task build:ext <name> [--out <dir>] [--target-dir <dir>]
//
// `extensions/<name>/tartan.json` decides the runtime:
// - `wasm` (a Rust crate, `extensions/<name>/Cargo.toml`):
//   1. `cargo build --release --target wasm32-unknown-unknown`;
//   2. `wasm-tools component new` (the crate's core module → a component);
//   3. `jco transpile --instantiation sync --no-typescript` (no JSPI): the
//      glue `ext.js` and the core modules `ext.core*.wasm`;
//   4. the import record `imports.json`, read from the core modules and
//      checked against the manifest's permissions, as publish checks it;
// - `js` (`extensions/<name>/src/index.ts`): one esbuild ESM bundle, `main.js`.
// Then it writes `<out>` (default `extensions/<name>/dist/`, never committed):
// the package files with `tartan.json` naming the built entry, `publish.json`
// (the `PUT /-/api/packages` body, validated by the kernel's own
// `checkBundle`, which also gives the package sha256) and, for wasm,
// `bundled.js` (the `wasm-bundled` registration: glue, core modules and
// migrations bundled into the Worker by the deploy).
//
// Tools: `cargo` (with the wasm32-unknown-unknown target) and `wasm-tools`
// on PATH (or `WASM_TOOLS`), jco from `node_modules/.bin/jco` (or `JCO`).
// `CARGO_TARGET_DIR` is honoured (one shared target directory, AGENTS.md).
//
// Deploy tooling only; runtime code never imports it.

import * as path from "node:path";
import { type Manifest, parseManifest } from "@tartan/contract";
import {
	checkBundle,
	requiredFiles,
} from "../src/kernel/exthost/api/packages.ts";
import {
	componentImports,
	importIssues,
} from "../src/kernel/exthost/registry/imports.ts";
import {
	denoRun,
	parseFlags,
	REPO_ROOT,
	type Run,
	UsageError,
} from "./preflight.ts";

export const USAGE =
	`Usage: deno task build:ext <name> [--out <dir>] [--target-dir <dir>]

  <name>              the directory under extensions/
  --out <dir>         output directory (default extensions/<name>/dist)
  --target-dir <dir>  cargo target directory (default $CARGO_TARGET_DIR or ./target)`;

export const WASM_TARGET = "wasm32-unknown-unknown";
export const GLUE = "ext.js";
export const JS_MAIN = "main.js";

export type BuildOptions = {
	readonly name: string;
	readonly out?: string;
	readonly targetDir?: string;
	readonly root?: string;
	readonly run?: Run;
	readonly env?: Readonly<Record<string, string | undefined>>;
	readonly log?: (line: string) => void;
};

export type BuildResult = {
	readonly out: string;
	readonly manifest: Manifest;
	readonly sha256: string;
	readonly files: ReadonlyMap<string, Uint8Array>;
	readonly imports?: readonly string[];
};

/** `[package] name` of a Cargo.toml. */
export const crateName = (cargoToml: string): string => {
	const pkg = /^\[package\]\s*$([\s\S]*?)(?=^\[|$(?![\s\S]))/m.exec(cargoToml);
	const name = pkg && /^\s*name\s*=\s*"([^"]+)"/m.exec(pkg[1]);
	if (!name) throw new UsageError("Cargo.toml has no [package] name");
	return name[1];
};

/** jco's core modules in instantiation order: `ext.core.wasm`, `ext.core2.wasm`, … */
export const coreOrder = (names: readonly string[]): string[] =>
	names
		.filter((n) => /^ext\.core\d*\.wasm$/.test(n))
		.sort((a, b) =>
			Number(/core(\d*)/.exec(a)?.[1] || "1") -
			Number(/core(\d*)/.exec(b)?.[1] || "1")
		);

const b64 = (bytes: Uint8Array): string => {
	let text = "";
	for (let i = 0; i < bytes.length; i += 0x8000) {
		text += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
	}
	return btoa(text);
};

const MIGRATION_FILE_RE = /(?:^|\/)(\d{1,4})_([A-Za-z0-9_-]{1,64})\.sql$/;

/** The `wasm-bundled` module: glue, core modules and migrations for the Worker bundle. */
export const bundledModule = (
	manifest: Manifest,
	sha256: string,
	files: ReadonlyMap<string, Uint8Array>,
): string => {
	const cores = manifest.entry.wasm ?? [];
	const migrations = (manifest.storage.migrations ?? []).map((p) => {
		const m = MIGRATION_FILE_RE.exec(p);
		if (m === null) throw new UsageError(`migration ${p} is not NNNN_name.sql`);
		return {
			n: Number(m[1]),
			name: m[2],
			sql: new TextDecoder().decode(files.get(p)),
		};
	});
	return [
		`// Generated by \`deno task build:ext\` for ${manifest.id}@${manifest.version}; never committed.`,
		`import { instantiate } from "./${manifest.entry.js}";`,
		...cores.map((c, i) => `import core${i} from "./${c}";`),
		"",
		"export const bundled = {",
		`\tmanifest: ${JSON.stringify(manifest)},`,
		`\tsha256: ${JSON.stringify(sha256)},`,
		"\tinstantiate,",
		`\tcores: { ${
			cores.map((c, i) => `${JSON.stringify(c)}: core${i}`).join(", ")
		} },`,
		`\tmigrations: ${JSON.stringify(migrations)},`,
		"};",
		"",
	].join("\n");
};

const exists = async (p: string): Promise<boolean> => {
	try {
		await Deno.stat(p);
		return true;
	} catch {
		return false;
	}
};

const must = async (
	run: Run,
	cmd: string,
	args: readonly string[],
	env?: Record<string, string>,
): Promise<void> => {
	const r = await run(cmd, args, { io: "tee", ...(env ? { env } : {}) });
	if (r.code !== 0) {
		throw new Error(`${cmd} ${args.join(" ")} failed (exit ${r.code})`);
	}
};

/** Builds one package and writes its output directory. */
export const buildExtension = async (
	options: BuildOptions,
): Promise<BuildResult> => {
	const root = options.root ?? REPO_ROOT;
	const run = options.run ?? denoRun;
	const env = options.env ?? Deno.env.toObject();
	const log = options.log ?? ((line: string) => console.log(line));
	if (!/^[a-z0-9][a-z0-9-]*$/.test(options.name)) {
		throw new UsageError(`not an extension directory name: ${options.name}`);
	}
	const dir = path.join(root, "extensions", options.name);
	const out = options.out ?? path.join(dir, "dist");
	const parsed = parseManifest(
		JSON.parse(await Deno.readTextFile(path.join(dir, "tartan.json"))),
	);
	if (!parsed.ok) {
		throw new UsageError(`tartan.json: ${parsed.errors.join("; ")}`);
	}
	const source = parsed.manifest;
	const files = new Map<string, Uint8Array>();
	let manifest: Manifest;
	let imports: string[] | undefined;
	const work = await Deno.makeTempDir({ prefix: "tartan-build-ext-" });
	try {
		if (source.runtime === "wasm") {
			const targetDir = options.targetDir ?? env.CARGO_TARGET_DIR ??
				path.join(root, "target");
			const crate = crateName(
				await Deno.readTextFile(path.join(dir, "Cargo.toml")),
			);
			log(`cargo build ${crate} (${WASM_TARGET}, release)`);
			await must(run, "cargo", [
				"build",
				"--release",
				"--target",
				WASM_TARGET,
				"--manifest-path",
				path.join(dir, "Cargo.toml"),
			], { CARGO_TARGET_DIR: targetDir });
			const core = path.join(
				targetDir,
				WASM_TARGET,
				"release",
				`${crate.replaceAll("-", "_")}.wasm`,
			);
			const component = path.join(work, "component.wasm");
			const wasmTools = env.WASM_TOOLS ?? "wasm-tools";
			log("wasm-tools component new");
			await must(run, wasmTools, ["component", "new", core, "-o", component]);
			const jco = env.JCO ?? path.join(root, "node_modules", ".bin", "jco");
			if (env.JCO === undefined && !await exists(jco)) {
				throw new UsageError(
					"jco is not installed: node_modules/.bin/jco is missing (npm ci), or set JCO",
				);
			}
			const jcoOut = path.join(work, "jco");
			log("jco transpile --instantiation sync");
			await must(run, jco, [
				"transpile",
				component,
				"-o",
				jcoOut,
				"--name",
				"ext",
				"--instantiation",
				"sync",
				"--no-nodejs-compat",
				"--no-typescript",
				"--no-wasi-shim",
				"-b",
				"0",
			]);
			const produced: string[] = [];
			for await (const e of Deno.readDir(jcoOut)) produced.push(e.name);
			const cores = coreOrder(produced);
			if (!produced.includes(GLUE) || cores.length === 0) {
				throw new Error(`jco produced ${produced.join(", ")}`);
			}
			files.set(GLUE, await Deno.readFile(path.join(jcoOut, GLUE)));
			for (const c of cores) {
				files.set(c, await Deno.readFile(path.join(jcoOut, c)));
			}
			const found = componentImports(cores.map((c) => files.get(c)!));
			const issues = [
				...found.foreign.map((i) => `import ${i} is outside tartan:ext`),
				...importIssues(found.imports, source.permissions),
			];
			if (issues.length > 0) {
				throw new UsageError(`imports ⊄ permissions: ${issues.join("; ")}`);
			}
			imports = found.imports;
			files.set(
				"imports.json",
				new TextEncoder().encode(`${JSON.stringify(imports, null, "\t")}\n`),
			);
			manifest = { ...source, entry: { js: GLUE, wasm: cores } };
		} else if (source.runtime === "js") {
			const esbuild = await import("esbuild");
			log("esbuild src/index.ts");
			const bundle = await esbuild.build({
				entryPoints: [path.join(dir, "src", "index.ts")],
				bundle: true,
				write: false,
				format: "esm",
				platform: "neutral",
				target: "es2023",
				external: ["cloudflare:*"],
				tsconfig: path.join(root, "tsconfig.json"),
				logLevel: "silent",
			});
			await esbuild.stop();
			files.set(JS_MAIN, bundle.outputFiles[0].contents);
			manifest = { ...source, entry: { js: JS_MAIN } };
		} else {
			throw new UsageError(
				`${source.id} is a ${source.runtime} package; build:ext builds js and wasm`,
			);
		}
		for (const p of requiredFiles(manifest)) {
			if (files.has(p)) continue;
			files.set(p, await Deno.readFile(path.join(dir, p)));
		}
		const checked = checkBundle({
			manifest,
			files: Object.fromEntries(
				[...files].map(([p, bytes]) => [p, b64(bytes)]),
			),
		});
		await Deno.remove(out, { recursive: true }).catch(() => {});
		for (const [p, bytes] of checked.files) {
			const target = path.join(out, p);
			await Deno.mkdir(path.dirname(target), { recursive: true });
			await Deno.writeFile(target, bytes);
		}
		const body = {
			manifest: checked.manifest,
			files: Object.fromEntries(
				[...files].map(([p, bytes]) => [p, b64(bytes)]),
			),
		};
		await Deno.writeTextFile(
			path.join(out, "publish.json"),
			JSON.stringify(body),
		);
		if (manifest.runtime === "wasm") {
			await Deno.writeTextFile(
				path.join(out, "bundled.js"),
				bundledModule(checked.manifest, checked.sha256, checked.files),
			);
		}
		const size = [...checked.files.values()].reduce(
			(n, b) => n + b.byteLength,
			0,
		);
		log(
			`${checked.manifest.id}@${checked.manifest.version}: ${checked.files.size} files, ${size} bytes, sha256 ${checked.sha256}`,
		);
		if (imports !== undefined) log(`imports: ${imports.join(", ")}`);
		log(`wrote ${path.relative(root, out) || out}`);
		return {
			out,
			manifest: checked.manifest,
			sha256: checked.sha256,
			files: checked.files,
			...(imports === undefined ? {} : { imports }),
		};
	} finally {
		await Deno.remove(work, { recursive: true }).catch(() => {});
	}
};

if (import.meta.main) {
	try {
		const args = Deno.args[0] === "--" ? Deno.args.slice(1) : Deno.args;
		const VALUE_FLAGS = ["--out", "--target-dir"];
		const at = args.findIndex((a, i) =>
			!a.startsWith("-") && !VALUE_FLAGS.includes(args[i - 1] ?? "")
		);
		const name = at === -1 ? undefined : args[at];
		const flags = parseFlags(args.filter((_, i) => i !== at), {
			out: "value",
			"target-dir": "value",
		});
		if (flags.has("help") || name === undefined) {
			console.log(USAGE);
			Deno.exit(name === undefined && !flags.has("help") ? 2 : 0);
		}
		await buildExtension({
			name,
			...(typeof flags.get("out") === "string"
				? { out: path.resolve(flags.get("out") as string) }
				: {}),
			...(typeof flags.get("target-dir") === "string"
				? { targetDir: path.resolve(flags.get("target-dir") as string) }
				: {}),
		});
	} catch (error) {
		console.error(
			`build:ext: ${error instanceof Error ? error.message : String(error)}`,
		);
		Deno.exit(error instanceof UsageError ? 2 : 1);
	}
}
